# Generated by Django 2.2.4 on 2019-08-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
    ]
