# Generated by Django 2.2.4 on 2019-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
            ],
        ),
    ]
