# Generated by Django 2.2.4 on 2019-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffriends', '0002_auto_20190829_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to='graffriends.Person'),
        ),
    ]
