# Generated by Django 2.2.4 on 2019-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graffriends', '0004_auto_20190829_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='followers', to='graffriends.Person'),
        ),
    ]
