# Generated by Django 2.2.4 on 2019-09-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graffriends', '0006_auto_20190903_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthday',
            new_name='Years',
        ),
    ]
