# Generated by Django 2.2.4 on 2019-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isdb', '0002_auto_20190829_0820'),
        ('imdb', '0003_movie_director'),
        ('graffriends', '0007_auto_20190903_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='favorite_album',
            field=models.ManyToManyField(to='isdb.Album'),
        ),
        migrations.AddField(
            model_name='person',
            name='favorite_films',
            field=models.ManyToManyField(to='imdb.Movie'),
        ),
    ]
